spaceone-dev/api

proto/spaceone/api/core/v1/query.proto
=> Add a distinct spec to StatisticsQuery

proto/spaceone/api/monitoring/plugin/log.proto, proto/spaceone/api/monitoring/plugin/metric.proto
=> Change monitoring plugin's request message

Dockerfile
=> Change package repository in Dockerfile

Makefile, bin/build.py
Update for API documentation at GitBook
- make file
- build.py
=> Update for API documentation at GitBook

proto/spaceone/api/config/v1/config_map.proto
config_map.proto doc api Normalization
=> config_map.proto doc api Normalization

proto/spaceone/api/config/v1/config_map.proto, proto/spaceone/api/identity/v1/user.proto
- config_map.proto
- user.proto
=> Provide additional information on comment

proto/spaceone/api/identity/v1/provider.proto, proto/spaceone/api/repository/v1/repository.proto
Add domain_id field to all APIs
=> Feature default domain

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/cloud_service_type.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/region.proto, proto/spaceone/api/inventory/v1/server.proto
Add state field to CloudService
Remove unused fields in Server
=> Change message description

proto/spaceone/api/inventory/v1/server.proto
=> Add ServerNIC and ServerDisk message

bin/build.py
- Copy version file into artifact due to github action
=> - Copy version file into artifact due to github action

proto/spaceone/api/core/v1/handler.proto, proto/spaceone/api/identity/v1/policy.proto, proto/spaceone/api/identity/v1/role.proto
=> Change authorization ptorobuf

proto/spaceone/api/inventory/v1/server.proto
=> Remove extra comment

proto/spaceone/api/core/v1/handler.proto, proto/spaceone/api/repository/v1/policy.proto
=> Change Authorization protobuf

proto/spaceone/api/plugin/v1/plugin.proto
- Added comments to plugin proto
=> - Added comments to plugin proto

proto/spaceone/api/statistics/v1/resource.proto, proto/spaceone/api/statistics/v1/schedule.proto
=> Change statistics formula protobuf

proto/spaceone/api/inventory/v1/collector.proto
=> Add metadata at plugin_info

proto/spaceone/api/sample/v1/helloworld.proto
=> Add a sample service

proto/spaceone/api/sample/v1/helloworld.proto
=> Change sample helloworld.proto

proto/spaceone/api/repository/v1/policy.proto
=> Change repository PolicyInfo message

Makefile
=> Add new Report API

proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/job_task.proto, proto/spaceone/api/inventory/v1/task_item.proto
=> Add inventory.Job JobTask TaskItem

docs/getting-started.md
Describe how to develop new gRPC protobuf.
=> Add getting-started.md

Makefile, proto/spaceone/api/power_scheduler/v1/schedule.proto
=> Add power_scheduler protobuf

proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto, proto/spaceone/api/inventory/v1/task_item.proto
=> Change inventory job spec

proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/inventory/v1/job.proto, proto/spaceone/api/inventory/v1/job_task.proto
=> Change Job JobTask API

proto/spaceone/api/core/v1/query.proto
=> Add date_format option to Stat Query

proto/spaceone/api/core/v1/query.proto
=> Change stat aggregate fields

proto/spaceone/api/repository/v1/policy.proto
added list in type if it's repeated in probuff
=> added list in type if it's repeated in probuff

proto/spaceone/api/repository/v1/policy.proto
=> sync up for list type

proto/spaceone/api/identity/plugin/auth.proto
Add new identity.Auth API
- Add init method
- Update verify method
- Add schema field
=> Update Auth API

proto/spaceone/api/inventory/plugin/collector.proto
=> Add options in inventory.Collector

proto/spaceone/api/inventory/v1/resource_group.proto
=> Add a options field to resource group

proto/spaceone/api/inventory/v1/resource_group.proto
=> Add a keyword filter to resource group settings

proto/spaceone/api/config/v1/domain_config.proto
=> Add config.DomainConfig

proto/spaceone/api/config/v1/user_config.proto
=> Change config's ConfigMap service to UserConfig service

proto/spaceone/api/power_scheduler/v1/domain.proto
=> Add enable/disable domain in power-scheduler

proto/spaceone/api/power_scheduler/v1/domain.proto
=> Update domain state

proto/spaceone/api/inventory/v1/cloud_service_type.proto, proto/spaceone/api/inventory/v1/server.proto
=> Change cloud service type and server protobuf

proto/spaceone/api/inventory/v1/region.proto
=> Change inventory region field (deleted_at -> updated_at)

proto/spaceone/api/inventory/v1/cloud_service_type.proto
=> Add is_primary and is_major fields to cloud service type

proto/spaceone/api/inventory/v1/cloud_service_type.proto
=> Add resource_type field to cloud service type

proto/spaceone/api/inventory/v1/cloud_service_type.proto
=> Bug fix: type error

proto/spaceone/api/statistics/v1/resource.proto, proto/spaceone/api/statistics/v1/schedule.proto
Change append field to concat field
=> Add a extend_data field to resource stat api

proto/spaceone/api/statistics/v1/resource.proto
=> Add a fill_na field to stat api

proto/spaceone/api/statistics/v1/resource.proto, proto/spaceone/api/statistics/v1/schedule.proto
=> Add a fill_na option to stat api

proto/spaceone/api/core/v1/query.proto
=> Add keyword option to StatisticsQuery

proto/spaceone/api/power_scheduler/v1/domain.proto
=> Update power-scheduler domain enable/disable

Makefile, proto/spaceone/api/billing/plugin/billing.proto, proto/spaceone/api/billing/plugin/data_source.proto, proto/spaceone/api/billing/v1/billing.proto, proto/spaceone/api/billing/v1/data_source.proto
=> Add billing API

proto/spaceone/api/identity/v1/endpoint.proto
=> Add endpoint api to identity service

proto/spaceone/api/identity/v1/project.proto, proto/spaceone/api/identity/v1/project_group.proto
=> Remove unused field in project (template_id and template_data)

proto/spaceone/api/identity/v1/project_group.proto
=> Change a tag format (dict -> list of dict)

proto/spaceone/api/billing/v1/billing.proto
=> Update billing API

proto/spaceone/api/billing/plugin/billing.proto, proto/spaceone/api/billing/v1/billing.proto
=> Change datetime to string

proto/spaceone/api/repository/v1/plugin.proto, proto/spaceone/api/repository/v1/policy.proto, proto/spaceone/api/repository/v1/schema.proto
=> Add updated_at field to repository plugin, policy and schema resources

Dockerfile
=> Fix a build error

.github/workflows/CI_pypi_devTest.yml
=> Change a build option

proto/spaceone/api/identity/v1/project.proto
=> Remove deleted_at field from project resource

proto/spaceone/api/identity/v1/project.proto, proto/spaceone/api/identity/v1/project_group.proto, proto/spaceone/api/identity/v1/role.proto, proto/spaceone/api/identity/v1/role_binding.proto, proto/spaceone/api/identity/v1/user.proto
=> Add role binding api and change related api fields

proto/spaceone/api/core/v1/handler.proto
=> Change authorization api messages

proto/spaceone/api/billing/plugin/billing.proto
Add minor description for billing requests on protobuff
=> Add minor description for billing requests on protobuff

proto/spaceone/api/inventory/v1/job_task.proto
- deleted_count
- disconnected_count
=> Add new field for job_task

proto/spaceone/api/core/v1/handler.proto
=> Add user_id field

proto/spaceone/api/core/v1/handler.proto
=> Add fields to authorization.verify

proto/spaceone/api/core/v1/query.proto
=> Change StatQuery Spec

proto/spaceone/api/statistics/v1/resource.proto, proto/spaceone/api/statistics/v1/schedule.proto
=> Change a statistics resource query spec

proto/spaceone/api/identity/v1/project_group.proto
=> Add filter to project group

proto/spaceone/api/secret/v1/secret.proto
=> Change secret api's response message

proto/spaceone/api/secret/v1/secret.proto
=> Add field to SecretDataInfo

proto/spaceone/api/secret/v1/secret.proto
=> Add a secret update_data method

proto/spaceone/api/secret/v1/secret.proto
=> Change a secret message's field name

proto/spaceone/api/monitoring/v1/data_source.proto
=> add metadata to pluginInfo

proto/spaceone/api/cost_saving/v1/cost_saving.proto
=> Fix a datetime file type (timestamp -> iso8601)

proto/spaceone/api/statistics/plugin/storage.proto, proto/spaceone/api/statistics/v1/schedule.proto, proto/spaceone/api/statistics/v1/storage.proto
Add storage plugin protobuf in statistics
Update schedule protobuf in statistics
=> Add storage protobuf in statistics

proto/spaceone/api/notification/v1/project_channel.proto, proto/spaceone/api/notification/v1/protocol.proto, proto/spaceone/api/notification/v1/user_channel.proto
=> Fix package path bug (monitoring -> notification)

proto/spaceone/api/monitoring/v1/maintenance_window.proto
=> Change monitoring service's field name

proto/spaceone/api/notification/v1/project_channel.proto, proto/spaceone/api/notification/v1/user_channel.proto
- project_channel.proto
- user_channel.proto
=> Add new proto for is_subscribe

proto/spaceone/api/notification/v1/project_channel.proto
=> Change rest url

proto/spaceone/api/notification/v1/project_channel.proto
=> Change notification_level's field type

proto/spaceone/api/monitoring/v1/escalation_policy.proto, proto/spaceone/api/monitoring/v1/maintenance_window.proto
=> Change monitoring alert system's apis

proto/spaceone/api/monitoring/v1/escalation_policy.proto
=> Fix duplicate enum fields

proto/spaceone/api/identity/v1/domain.proto
- change_auth_plugin
- update_plugin
- verify_plugin
=> Add identity.Domain

proto/spaceone/api/notification/v1/notification.proto
=> Add new proto for notification.proto

proto/spaceone/api/monitoring/plugin/event.proto, proto/spaceone/api/monitoring/plugin/webhook.proto, proto/spaceone/api/notification/plugin/notification.proto, proto/spaceone/api/notification/plugin/webhook.proto
- monitoring/event.proto
- monitoring/webhook.proto
- notification/notification.proto
- notification/webhook.proto
=> Add plugin protos for monitoring, notification

proto/spaceone/api/statistics/v1/storage.proto
Add VerifyInfo message to storage proto buf
=> Add VerifyInfo message to storage proto buf

proto/spaceone/api/statistics/v1/storage.proto
Remove VerifyInfo from storage buf
=> Remove VerifyInfo from storage buf

proto/spaceone/api/monitoring/plugin/event.proto
Update event.proto for wbehook
=> Update event.proto for wbehook

proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/event.proto, proto/spaceone/api/monitoring/v1/project_alert_config.proto, proto/spaceone/api/monitoring/v1/webhook.proto
=> Change monitoring alert's APIS

proto/spaceone/api/monitoring/plugin/event.proto
Update for event.proto for occurred_at
=> Update for event.proto for occurred_at

proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/event.proto
=> Change monitoring alert's API Spec

proto/spaceone/api/monitoring/v1/alert.proto
=> Add filter to AlertQuery

proto/spaceone/api/monitoring/v1/event.proto
=> Change create event response

proto/spaceone/api/monitoring/plugin/event.proto
=> raw_data -> data

proto/spaceone/api/monitoring/v1/event_rule.proto
=> Add monitoring.EventRule APIs

proto/spaceone/api/monitoring/v1/event_rule.proto
=> Change event rule's field name

proto/spaceone/api/monitoring/v1/event_rule.proto
=> Change event rule's message name

proto/spaceone/api/monitoring/v1/event_rule.proto
=> Add field to monitoring EventRule

proto/spaceone/api/monitoring/plugin/webhook.proto
initPlugin -> WebhookInitRequest
PluginVerifyRequest ->WebhookPluginVerifyRequest
=> [CLOUD-4722] Update Webhook in webhook.proto

proto/spaceone/api/monitoring/v1/alert.proto
=> Add field to monitoring.Alert

proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/event.proto
=> Remove ip address field

proto/spaceone/api/monitoring/v1/alert.proto
=> Add error state to alert resource

proto/spaceone/api/identity/v1/project.proto, proto/spaceone/api/identity/v1/project_group.proto
=> Change field type of identity.Project

proto/spaceone/api/identity/v1/project.proto
=> Add field to project resource

proto/spaceone/api/monitoring/plugin/event.proto
=> Add desc in ParseRequest

proto/spaceone/api/identity/v1/endpoint.proto
add request parameter
- endpoint_type(string): public(default) | internal
=> Add endpoint_type in identity.Endpoint

proto/spaceone/api/identity/v1/token.proto
=> Change identity field description

proto/spaceone/api/identity/v1/project.proto, proto/spaceone/api/identity/v1/project_group.proto
=> feat: Add option when adding project members

proto/spaceone/api/monitoring/v1/project_alert_config.proto
=> fix: change monitoring service's fields

proto/spaceone/api/monitoring/v1/alert.proto
=> refactor: change monitoring service's update arguments

proto/spaceone/api/identity/v1/domain.proto
=> feat: add field

proto/spaceone/api/billing/v1/data_source.proto, proto/spaceone/api/inventory/v1/collector.proto, proto/spaceone/api/monitoring/v1/data_source.proto, proto/spaceone/api/monitoring/v1/webhook.proto
=> feat: add upgrade_mode field to PluginInfo

proto/spaceone/api/monitoring/v1/data_source.proto
=> refactor: change monitoring data source's response message

proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/event.proto
=> feat: add field to monitoring.Alert and monitoring.Event

proto/spaceone/api/repository/v1/plugin.proto
=> refactor: change registry_type field type

proto/spaceone/api/repository/v1/plugin.proto
=> refactor: add registry config to repository plugin

proto/spaceone/api/cost_analysis/v1/dashboard.proto
=> feat: add field to cost_analysis.Dashboard

proto/spaceone/api/core/v1/query.proto
=> feat: add push operator to stat query

proto/spaceone/api/repository/v1/policy.proto
added state parameter for repository policy protobuffer
=> feat: add state param

proto/spaceone/api/repository/v1/policy.proto, proto/spaceone/api/repository/v1/schema.proto
Added schema_id, state parameter for schema
Updated state parameter for policy
=> feat: add schema_id, state

proto/spaceone/api/repository/v1/policy.proto
updated policy protobuffer field number
=> fix: update state field number

proto/spaceone/api/cost_analysis/v1/budget_usage.proto
=> feat: change budget usage APIs

proto/spaceone/api/cost_analysis/v1/cost.proto
=> feat: add field to cost resource

proto/spaceone/api/cost_analysis/v1/exchange_rate.proto
=> fix: fix response message

proto/spaceone/api/core/v1/query.proto
=> feat: add sub condition to aggregate group field

proto/spaceone/api/inventory/v1/job_task.proto
=> fix: fix wrong enum values

proto/spaceone/api/secret/v1/secret.proto
=> feat: add field to Secret.update_data API

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/server.proto
=> refactor: change server and cloud service fields

proto/spaceone/api/cost_analysis/v1/budget.proto, proto/spaceone/api/cost_analysis/v1/budget_usage.proto
=> refactor: change budget and budget usage fields and query

proto/spaceone/api/cost_analysis/v1/budget_usage.proto
=> refactor: change query filter

proto/spaceone/api/cost_analysis/plugin/cost.proto
=> feat: change cost analysis plugin's response message type

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/plugin/job.proto
=> fix: fix wrong package path

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/plugin/job.proto
=> refactor: change fields

proto/spaceone/api/cost_analysis/v1/cost.proto
=> refactor: add field to cost_analysis.Cost

proto/spaceone/api/cost_analysis/plugin/job.proto
=> refactor: add field

proto/spaceone/api/cost_analysis/plugin/job.proto
=> refactor: change field name

proto/spaceone/api/cost_analysis/plugin/job.proto, proto/spaceone/api/cost_analysis/v1/data_source.proto
=> refactor: remove unused field

proto/spaceone/api/cost_analysis/v1/data_source.proto
=> refactor: change response

proto/spaceone/api/cost_analysis/v1/job_task.proto
=> feat: change cost analysis's job task fields

proto/spaceone/api/core/v1/query.proto
=> feat: add query options to stat query

proto/spaceone/api/cost_analysis/plugin/job.proto
=> refactor: change cost analysis's data source plugin interface

proto/spaceone/api/cost_analysis/v1/job.proto
=> refactor: change cost analysis's job response

proto/spaceone/api/config/v1/domain_config.proto, proto/spaceone/api/config/v1/user_config.proto
=> refactor: add USER scope for authorization

proto/spaceone/api/cost_analysis/v1/job_task.proto
=> feat: change cost analysis's fields

proto/spaceone/api/cost_analysis/v1/cost.proto
=> refactor: add start end field to cost resource

proto/spaceone/api/cost_analysis/plugin/cost.proto, proto/spaceone/api/cost_analysis/v1/cost.proto
=> refactor: change cost resource's fields

proto/spaceone/api/cost_analysis/v1/cost.proto
=> feat: add cost analyze API

proto/spaceone/api/inventory/v1/cloud_service.proto, proto/spaceone/api/inventory/v1/server.proto
=> feat: add field to server and cloud_service

proto/spaceone/api/notification/v1/notification.proto
=> feat: add push request

proto/spaceone/api/notification/v1/notification.proto
=> fix: fix typo

proto/spaceone/api/config/v1/domain_config.proto, proto/spaceone/api/config/v1/user_config.proto
=> feat: change user and domain config fields

Dockerfile
=> build: modify command in dockerfile

proto/spaceone/api/config/v1/user_config.proto
=> doc: change docs

proto/spaceone/api/cost_analysis/v1/exchange_rate.proto
=> feat: add APIs of cost_analysis.ExchangeRate

proto/spaceone/api/monitoring/plugin/event.proto, proto/spaceone/api/monitoring/v1/alert.proto, proto/spaceone/api/monitoring/v1/event.proto
Add provider field, account field
=> Feat: add provider field, account field

proto/spaceone/api/cost_analysis/v1/data_source.proto, proto/spaceone/api/cost_analysis/v1/job.proto
=> feat: add options field to cost_analysis.Job

Makefile, proto/spaceone/api/board/v1/board.proto, proto/spaceone/api/board/v1/post.proto
=> feat: add APIs of board microservice

proto/spaceone/api/board/v1/post.proto
Signed-off-by: Seolmin Kwon <seolmin@megazone.com>
[related PR of Board microservices](https://github.com/spaceone-dev/board/pull/12)
=> refactor: change options to dict

proto/spaceone/api/notification/v1/notification_usage.proto, proto/spaceone/api/notification/v1/quota.proto
feat: add notification quota and usage
[Add feature to metering and quota for sending notifications](https://github.com/spaceone-dev/notification/issues/86)
=> feat: add notification quota and usage

proto/spaceone/api/identity/v1/role.proto
=> feat: add page_permissions field to identity.Role

Makefile
=> build: change services to build gRPC

.github/PULL_REQUEST_TEMPLATE.md, proto/spaceone/api/inventory/v1/cloud_service.proto
feat: add ip_addresses in inventory cloud service
[AWS EC2] Migrate Server Resources to Cloud Service Resources ([#72](https://github.com/spaceone-dev/plugin-aws-ec2-inven-collector/issues/72))
=> feat: add ip_addresses in inventory cloud service

proto/spaceone/api/inventory/v1/cloud_service.proto
feat: add ip_address in cloud service query
[AWS EC2] Migrate Server Resources to Cloud Service Resources [#72](https://github.com/spaceone-dev/plugin-aws-ec2-inven-collector/issues/72)
=> feat: add ip_address in cloud service query

proto/spaceone/api/statistics/v1/resource.proto
=> feat: support for multiple sort keys in stat query

proto/spaceone/api/notification/v1/notification_usage.proto
=> feat: add fail_count in notification usage

proto/spaceone/api/monitoring/v1/log.proto
refactor: modify LogRequest for Monitoring log list
Refactoring Monitoring Log ([#206](https://github.com/spaceone-dev/monitoring/issues/206))
=> refactor: modify LogRequest for Monitoring log list

proto/spaceone/api/monitoring/plugin/log.proto
refactor: modify LogRequest for Monitoring Plugin log list
Refactoring Monitoring Log ([#206](https://github.com/spaceone-dev/monitoring/issues/206))
=> refactor: modify LogRequest for Monitoring Plugin log list

proto/spaceone/api/monitoring/plugin/log.proto
refactor: modify LogDataInfo for Monitoring Plugin log list
=> refactor: modify LogDataInfo for Monitoring Plugin log list

proto/spaceone/api/inventory/v1/change_history.proto, proto/spaceone/api/inventory/v1/cloud_service.proto
- Add ChangeHistory APIs
- Remove pin_data API
=> Change Inventory APIs

proto/spaceone/api/inventory/v1/note.proto
- change field name
- change rest api path
=> refactor: change note service's fields

proto/spaceone/api/inventory/v1/change_history.proto
- Add diff_count field to inventory.ChangeHistory
=> feat: add diff_count field

proto/spaceone/api/inventory/v1/cloud_service.proto
=> refactor: remove launched_at field

proto/spaceone/api/inventory/v1/change_history.proto
=> refactor: add updated_by field

proto/spaceone/api/inventory/v1/change_history.proto
=> refactor: change require field (cloud_service_id)

proto/spaceone/api/inventory/v1/change_history.proto
=> refactor: change diff field type

proto/spaceone/api/monitoring/plugin/log.proto, proto/spaceone/api/monitoring/plugin/metric.proto, proto/spaceone/api/monitoring/v1/metric.proto
refactor: modify Metric/Log for Monitoring
Refactoring Monitoring Metric ([#207](https://github.com/spaceone-dev/monitoring/issues/207))
Refactoring Monitoring Log ([#206](https://github.com/spaceone-dev/monitoring/issues/206))
=> refactor: modify Metric/Log for Monitoring

proto/spaceone/api/monitoring/plugin/metric.proto
=> fix: modify unit type

proto/spaceone/api/monitoring/v1/metric.proto
=> refactor: modify MetricInfo

proto/spaceone/api/monitoring/v1/metric.proto
=> refactor: modify query

proto/spaceone/api/monitoring/plugin/log.proto, proto/spaceone/api/monitoring/v1/log.proto
refactor: modify Log data results
=> refactor: modify Log data results

proto/spaceone/api/identity/v1/token.proto, proto/spaceone/api/identity/v1/user.proto, proto/spaceone/api/inventory/v1/change_history.proto
=> add set_required_actions API

proto/spaceone/api/monitoring/plugin/metric.proto
fix: modify MetricDataInfo (values)
=> fix: modify MetricDataInfo (values)

proto/spaceone/api/board/v1/post.proto
I added user_domain_id in post info
The test code works fine.
=> fix: add user_domain_id in post info

Makefile, proto/spaceone/api/file_manager/v1/file.proto
=> feat: add file_manager APIs

proto/spaceone/api/notification/v1/notification.proto
feat: update delete_all in Notification protobuf
=> feat: update delete_all in Notification protobuf

proto/spaceone/api/notification/v1/notification.proto
refactor: modify delete notifications for multiple
=> refactor: modify delete notifications for multiple

proto/spaceone/api/board/v1/post.proto, proto/spaceone/api/core/v1/handler.proto
=> refactor authorization
